FROM node:14

WORKDIR /app

ENV HOST="0.0.0.0"

COPY package.json ./
COPY yarn.lock ./
COPY tsconfig.json ./
COPY packages/server/package.json ./packages/server/
COPY packages/server/tsconfig.json ./packages/server/

RUN yarn --frozen-lockfile

COPY packages/server/prisma ./packages/server/
RUN yarn workspace server prisma:generate

COPY packages/server packages/server
RUN yarn build:server

EXPOSE 8000

CMD PORT=$PORT NODE_ENV=production yarn start:server