version: "3.1"
services:
  db:
    image: postgres:13.4
    container_name: "db"
    restart: always
    user: root
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: password
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "app"
    depends_on:
      - db
    tty: true
    ports:
      - "8000:8000"
    environment:
      HOST: 0.0.0.0
    expose:
      - 8000
volumes:
  postgres:
